### ISSUE TITLE
P2P Code Review

### ISSUE THREAD

**Issue by kakarrot92** [youmari/Capstone-project1#7]
**Highlights**
Site is responsible for mobile and desktop versions
Good semantically written code

**Feedbacks**
Icons of "Main program" section are overflowing from the background container

**Comment by edwardoluyara** [comment]
For me the Icons as well are not in a static position they overflow.
Why not add `overflowX: hidden` to the container to see how It works
Apart from that your site looks great
I'll also say clean code
"Well done @youmari "

**Comment by youmari** [comment]
Thanks guys 💯
